Flask-SocketIO 서버를 http://0.0.0.0:5001 에서 시작합니다...
INFO:app.sockets.events:클라이언트 연결됨: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
WARNING:app.sockets.events:Camera 1 is already streaming for client jlrnjiZjTJeR4mmoAAAC
WARNING:app.sockets.events:Camera 1 is already streaming for client jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
WARNING:app.sockets.events:중지할 스트리밍 작업이 없습니다: camera_id=0, client=jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
WARNING:app.sockets.events:Camera 1 is already streaming for client jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:0@42.034] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:0@42.066] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:1@45.070] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:1@45.072] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:0@47.749] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:0@47.752] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:0@50.435] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:0@50.438] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[person 탐지] 카메라 0에서 이벤트 발생. confidence: 0.82, 녹화를 시작합니다.
Traceback (most recent call last):
  File "E:\anaconda\envs\bss\lib\site-packages\mysql\connector\connection_cext.py", line 555, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unknown column 'cameras.source' in 'field list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "E:\anaconda\envs\bss\lib\site-packages\mysql\connector\cursor_cext.py", line 276, in execute
    result = self._cnx.cmd_query(
  File "E:\anaconda\envs\bss\lib\site-packages\mysql\connector\connection_cext.py", line 563, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'cameras.source' in 'field list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\anaconda\envs\bss\lib\site-packages\eventlet\hubs\hub.py", line 476, in fire_timers
    timer()
  File "E:\anaconda\envs\bss\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "E:\anaconda\envs\bss\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\video_service.py", line 229, in start_video_processing
    camera = Camera.query.get(int(camera_id_for_db) + 1)
  File "<string>", line 2, in get
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\util\deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\orm\query.py", line 943, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\orm\query.py", line 947, in _get_impl
    return self.session._get_impl(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\orm\session.py", line 2912, in _get_impl
    return db_load_fn(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\orm\loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\orm\session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\sql\elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "E:\anaconda\envs\bss\lib\site-packages\mysql\connector\cursor_cext.py", line 276, in execute
    result = self._cnx.cmd_query(
  File "E:\anaconda\envs\bss\lib\site-packages\mysql\connector\connection_cext.py", line 563, in cmd_query
    raise get_mysql_exception(
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'cameras.source' in 'field list'
[SQL: SELECT cameras.id AS cameras_id, cameras.camera_name AS cameras_camera_name, cameras.source AS cameras_source, cameras.location AS cameras_location, cameras.status AS cameras_status
FROM cameras
WHERE cameras.id = %(pk_1)s]
[parameters: {'pk_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:1@57.066] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:1@57.069] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:2@59.718] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:2@59.720] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:3@62.386] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:3@62.388] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:3@65.047] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:3@65.050] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
[person 탐지] 카메라 0에서 이벤트 발생. confidence: 0.92, 녹화를 시작합니다.
Traceback (most recent call last):
  File "E:\anaconda\envs\bss\lib\site-packages\mysql\connector\connection_cext.py", line 555, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unknown column 'cameras.source' in 'field list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "E:\anaconda\envs\bss\lib\site-packages\mysql\connector\cursor_cext.py", line 276, in execute
    result = self._cnx.cmd_query(
  File "E:\anaconda\envs\bss\lib\site-packages\mysql\connector\connection_cext.py", line 563, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'cameras.source' in 'field list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\anaconda\envs\bss\lib\site-packages\eventlet\hubs\hub.py", line 476, in fire_timers
    timer()
  File "E:\anaconda\envs\bss\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "E:\anaconda\envs\bss\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\video_service.py", line 229, in start_video_processing
    camera = Camera.query.get(int(camera_id_for_db) + 1)
  File "<string>", line 2, in get
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\util\deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\orm\query.py", line 943, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\orm\query.py", line 947, in _get_impl
    return self.session._get_impl(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\orm\session.py", line 2912, in _get_impl
    return db_load_fn(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\orm\loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\orm\session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\sql\elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "E:\anaconda\envs\bss\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "E:\anaconda\envs\bss\lib\site-packages\mysql\connector\cursor_cext.py", line 276, in execute
    result = self._cnx.cmd_query(
  File "E:\anaconda\envs\bss\lib\site-packages\mysql\connector\connection_cext.py", line 563, in cmd_query
    raise get_mysql_exception(
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'cameras.source' in 'field list'
[SQL: SELECT cameras.id AS cameras_id, cameras.camera_name AS cameras_camera_name, cameras.source AS cameras_source, cameras.location AS cameras_location, cameras.status AS cameras_status
FROM cameras
WHERE cameras.id = %(pk_1)s]
[parameters: {'pk_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/f405)
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:2@67.726] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:2@67.729] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:0@70.268] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:0@70.270] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:Requesting to start stream: camera_id=0, model=yolo11n_early_fusion.pt, client=jlrnjiZjTJeR4mmoAAAC
'C:\Users\hr0833\Desktop\한화에어로스페이스 스마트국방데이터분석과정\Project2\BSC_MultiSpectral_Model_DashBoard\backend\app\services\..\..\models_ai\yolo11n_early_fusion.pt' 모델 로드 성공.
카메라 0 스트리밍 시작 (모델: yolo11n_early_fusion.pt)
[ WARN:0@72.896] global cap_msmf.cpp:476 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:0@72.898] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
INFO:app.sockets.events:사용자 요청으로 카메라 1 스트리밍 중지: jlrnjiZjTJeR4mmoAAAC
INFO:app.sockets.events:클라이언트 연결 끊어짐: jlrnjiZjTJeR4mmoAAAC